name: CI

on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.MY_SECRET_NAME }}
      run: |
        echo "$SUPER_SECRET"

